# Generated by Django 3.1.1 on 2020-11-24 19:32

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201125_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=post.models.uuid_name, verbose_name='사진'),
        ),
    ]
