# Generated by Django 3.1.1 on 2020-11-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='재료명')),
                ('gram', models.PositiveIntegerField(verbose_name='그램수')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
            ],
        ),
    ]
