# Generated by Django 3.1.1 on 2020-11-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='gram',
        ),
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='사진'),
        ),
    ]
