# Generated by Django 3.1.1 on 2020-11-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='시장명')),
                ('photo', models.CharField(max_length=50, verbose_name='사진')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
            ],
        ),
    ]
