# Generated by Django 3.1.1 on 2020-11-24 17:45

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20201125_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='photo',
            field=models.ImageField(upload_to=market.models.uuid_name, verbose_name='사진'),
        ),
    ]
