# Generated by Django 3.1.1 on 2020-11-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mealkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='밀키트명')),
                ('photo', models.CharField(max_length=50, verbose_name='사진')),
                ('detail', models.CharField(max_length=50, verbose_name='상세설명')),
                ('signiture', models.BooleanField(verbose_name='시그니처')),
                ('price', models.PositiveIntegerField(verbose_name='최소가격')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='재료명')),
                ('photo', models.CharField(max_length=50, verbose_name='사진')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('mealkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealkit.mealkit')),
            ],
        ),
    ]
